---
- name: import gpg-keys
  rpm_key: state=present key={{ item }}
  with_items:
    - http://apt.sw.be/RPM-GPG-KEY.dag.txt
    - http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6
    - http://rpms.famillecollet.com/RPM-GPG-KEY-remi
  ignore_errors: true

- name: install repositories
  yum: name={{ item }} state=installed
  with_items:
    - http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
    - http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
  ignore_errors: true

# - name: Upgrade all currently install packages
#   yum: name=* state=latest

- name: Install libselinux-python
  yum: name=libselinux-python state=latest

- name: selinux setenforce 0
  command: setenforce 0
  ignore_errors: true

- name: disable selinux
  selinux: state=disabled

- name: Set hostname
  hostname: name="{{ hostname }}"

- name: Create user groups
  group: name="{{ item.name }}" system="{{ item.system }}" state=present
  with_items: user_groups

- name: Add sudo groups to sudoers list
  lineinfile: "dest=/etc/sudoers state=present regexp='^%{{ item }}' line='%{{ item }} ALL=(ALL) NOPASSWD: ALL'"
  with_items: user_sudo_groups

- name: Create user accounts
  user: name="{{ item.key }}" comment="{{ item.value.name }}" group="{{ item.value.group }}"
  with_dict: users

- name: Add authorized_keys
  authorized_key: user={{ item.key }} key="{{ item.value }}"
  with_dict: authorized_keys

- name: Install common apps
  yum: name={{ item }} state=latest
  with_items:
    - wget
    - htop
    - git


