---
- name: Install plex
  yum: name=https://downloads.plex.tv/plex-media-server/0.9.11.7.803-87d0708/plexmediaserver-0.9.11.7.803-87d0708.x86_64.rpm state=present

- name: Make sure that plex is started
  service: name=plexmediaserver state=started

- name: Add plex to iptables
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ item }} -j ACCEPT
  with_items:
    - 32400
    - 32410
    - 32412
    - 32414
  notify:
    - save iptables
    - restart iptables
