---
- name: Install nginx dependancies
  yum: name={{ item }} state=present
  with_items:
    - nginx

- name: Ensure nginx daemon  is started
  action: service name=nginx state=started

- name: Setup nginx firewall rules
  command: "/sbin/iptables -I INPUT 1 -p tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - 80
  notify:
    - save iptables
    - restart iptables
