---
- name: Add sabnzbd repo
  apt_repository: repo='ppa:jcfp/ppa' state=present

- name: Install sabnzbd
  apt: name={{ item }} state=present
  with_items:
    - sabnzbdplus
    - sabnzbdplus-theme-mobile

- name: Configure sabnzbd to run as a service (to be replaced with config template)
  lineinfile: dest=/etc/default/sabnzbdplus regexp=^{{ item.regex }}= line={{ item.regex }}={{ item.value }}
  with_items:
    - {regex: USER, value: plex}
    - {regex: HOST, value: 0.0.0.0}

- name: Startup sabnzbd
  service: name=sabnzbdplus state=started
  sudo: yes
