---
# Install and configure samba server (requires ports 137, 138, 139, 445 open).
- name: Ensure Samba-related packages are installed.
  yum: pkg={{ item }} state=installed
  with_items:
  - samba
  - samba-client
  - samba-common
  - cifs-utils
  notify: restart smb

- name: Configure samba
  template: src=smb.j2 dest=/etc/samba/smb.conf
  notify: restart smb

- name: Setup samba firewall rules
  command: "/sbin/iptables -I INPUT 1 -p tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - 137
    - 138
    - 139
    - 445
  notify:
    - save iptables
    - restart iptables
